### ISSUE TITLE
Occasionally starts refusing to open new memo/pester windows 

### ISSUE THREAD

**Issue by SunsetTech** [kiooeht/pesterchum#16]
After some series of events (what exactly is unknown) pesterchum will stop opening new memo/pester windows, the only way to fix this seems to be to restart the program.
No idea yet how to reproduce. will gather error messages if it starts happening again.

**Comment by SunsetTech** [comment]
got this error message recently

Could not parse stylesheet of widget 0x4c5e6a0
Traceback (most recent call last):
  File "pesterchum.py", line 2069, in joinSelectedMemo
  File "pesterchum.py", line 1450, in newMemo
  File "/home/brachyonic/Pesterchum/memos.py", line 502, in **init**
  File "/home/brachyonic/Pesterchum/profile.py", line 60, in log
TypeError: arguments did not match any overloaded call:
  QMessageBox(QWidget parent=None): argument 1 has unexpected type 'PesterLog'
  QMessageBox(QMessageBox.Icon, QString, QString, QMessageBox.StandardButtons buttons=QMessageBox.NoButton, QWidget parent=None, Qt.WindowFlags flags=Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 1 has unexpected type 'PesterLog'
  QMessageBox(QString, QString, QMessageBox.Icon, int, int, int, QWidget parent=None, Qt.WindowFlags flags=Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 1 has unexpected type 'PesterLog'

Seems to have happened when clickin on memo link, join memo window opened, channel joined was broken and I guess not actually joined. Now join memo window does not open.

**Comment by SunsetTech** [comment]
Caused by animated smilies code
